name: Feature Request
description: Suggest an idea or a new registry
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: I'm always frustrated when …
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: If proposing a new registry, include its search and details API URLs.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
